Document: iot
Title: Debian iot Manual
Author: <insert document author here>
Abstract: This manual describes what iot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iot/iot.sgml.gz

Format: postscript
Files: /usr/share/doc/iot/iot.ps.gz

Format: text
Files: /usr/share/doc/iot/iot.text.gz

Format: HTML
Index: /usr/share/doc/iot/html/index.html
Files: /usr/share/doc/iot/html/*.html
