#!/bin/sh
#                                                                                                                                                                                                  
# Licensed to the Apache Software Foundation (ASF) under one or more                                                                                                                               
# contributor license agreements.  See the NOTICE file distributed with                                                                                                                            
# this work for additional information regarding copyright ownership.                                                                                                                              
# The ASF licenses this file to You under the Apache License, Version 2.0                                                                                                                          
# (the "License"); you may not use this file except in compliance with                                                                                                                             
# the License.  You may obtain a copy of the License at                                                                                                                                            
#                                                                                                                                                                                                  
#    http://www.apache.org/licenses/LICENSE-2.0                                                                                                                                                    
#                                                                                                                                                                                                  
# Unless required by applicable law or agreed to in writing, software                                                                                                                              
# distributed under the License is distributed on an "AS IS" BASIS,                                                                                                                                
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                                                                                                         
# See the License for the specific language governing permissions and                                                                                                                              
# limitations under the License.                                                                                                                                                                   
#                                                                                                                                                                                                  

# echo stdin to stdout.  terminate after <terminateCount> lines
USAGE="$0 [<terminateCount>]"

#set -x

TERM_COUNT=0
if [ $# -gt 0 ]; then
  TERM_COUNT=$1
  shift
fi

COUNTER=0
while read LINE; do
  echo $LINE
  # echo $0 echoing $LINE >/dev/stderr
  COUNTER=$(($COUNTER+1))
  if [ $TERM_COUNT -gt 0 -a $COUNTER -ge $TERM_COUNT ]; then
    echo $0 TERMINATING after $LINE >/dev/stderr
    exit 1;
  fi
done